version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: siloam_emr_db
    environment:
      POSTGRES_USER: siloam
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siloam -d patient_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
